### ISSUE TITLE
How to run the unit tests test_pipeline.py?

### ISSUE THREAD

**Issue by ramsey-coding** [FudanSELab/ClassEval#4]
How to run the unit tests test_pipeline.py? Can you provide some more details for running the unit tests?

**Comment by wkx228** [comment]
> How to run the unit tests test_pipeline.py? Can you provide some more details for running the unit tests?

You can run `evaluation.py`, following [README](https://github.com/FudanSELab/ClassEval/tree/master/classeval_evaluation). Or if you want to customize your test pipeline, you can modify `test_pipeline.py` file. Feel free to let us know if you have any specific questions.
