### ISSUE TITLE
Question about the total number of methods in the benchmark

### ISSUE THREAD

**Issue by ztwater** [FudanSELab/ClassEval#6]
Hi, I noticed that the paper declares that the ClassEval benchmark includes 412 methods. However, I only got 410 of them in your latest data (By simply collecting all methods in the `methods_info` list). Could you please explain which two methods are excluded and why? Many thanks!

**Comment by wkx228** [comment]
We have updated our benchmark, so the statistics of the latest version may differ slightly from those given in the paper.

**Comment by DXY-lemon** [comment]
We have updated the README with the latest statistics, and thank you for carefully pointing out the issue! We removed two methods related to file handling due to testability issue.

**Comment by ztwater** [comment]
Thanks for your responses!
